import { Inter } from 'next/font/google'
import './globals.css'
import '@radix-ui//themes/styles.css'
import {Theme} from '@radix-ui/themes';
import HeaderNavigation from '@/common/HeaderNavigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Costume Dev NextJS App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderNavigation/>
        <Theme>{children}</Theme>
      </body>
    </html>
  )
}
